//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 02:12:09 PM CET 
//


package com.xmlproject.project_poverenik.model.xml_opste;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_opste package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_opste
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOrgan }
     * 
     */
    public TOrgan createTOrgan() {
        return new TOrgan();
    }

    /**
     * Create an instance of {@link TDodatneInformacije }
     * 
     */
    public TDodatneInformacije createTDodatneInformacije() {
        return new TDodatneInformacije();
    }

    /**
     * Create an instance of {@link TOsoba }
     * 
     */
    public TOsoba createTOsoba() {
        return new TOsoba();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TZakon }
     * 
     */
    public TZakon createTZakon() {
        return new TZakon();
    }

    /**
     * Create an instance of {@link TDatum }
     * 
     */
    public TDatum createTDatum() {
        return new TDatum();
    }

    /**
     * Create an instance of {@link TClanZakona }
     * 
     */
    public TClanZakona createTClanZakona() {
        return new TClanZakona();
    }

    /**
     * Create an instance of {@link TTrazilac }
     * 
     */
    public TTrazilac createTTrazilac() {
        return new TTrazilac();
    }

    /**
     * Create an instance of {@link TIdResenja }
     * 
     */
    public TIdResenja createTIdResenja() {
        return new TIdResenja();
    }

}
