package com.organ.project_organ.ws.poruka;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.149+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "PorukaService", 
                  wsdlLocation = "classpath:wsdl/Poruka.wsdl",
                  targetNamespace = "http://soap.spring.com/ws/Poruka") 
public class PorukaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.spring.com/ws/message", "PorukaService");
    public final static QName PorukaPort = new QName("http://soap.spring.com/ws/message", "PorukaPort");
    static {
        URL url = PorukaService.class.getClassLoader().getResource("wsdl/Poruka.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PorukaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Poruka.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PorukaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PorukaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PorukaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PorukaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PorukaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PorukaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Poruka
     */
    @WebEndpoint(name = "PorukaPort")
    public PorukaInterface getPorukaPort() {
        return super.getPort(PorukaPort, PorukaInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Poruka
     */
    @WebEndpoint(name = "PorukaPort")
    public PorukaInterface getPorukaPort(WebServiceFeature... features) {
        return super.getPort(PorukaPort, PorukaInterface.class, features);
    }

}
