
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.organ.project_organ.ws.poruka;

import com.organ.project_organ.model.poruka.Poruka;
import com.organ.project_organ.repository.impl.PorukaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.123+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "PorukaService",
                      portName = "PorukaPort",
                      targetNamespace = "http://soap.spring.com/ws/message",
                     // wsdlLocation = "classpath:wsdl/Hello.wsdl",
                      endpointInterface = "com.organ.project_organ.ws.poruka.PorukaInterface")
@Component
public class PorukaPortImpl implements PorukaInterface {
	@Autowired
	private com.organ.project_organ.service.PorukaService porukaService;

	@Override
	public boolean sendMessage(Poruka msg) {
		if (porukaService.saveMessage(msg)) {
			System.out.println("[" + msg.getVreme() + "] Nova poruka: " + msg.getTelo());
			return true;
		}
		return false;
	}

}
