//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 04:53:21 PM CET 
//


package rs.ac.uns.ftn.xml_obavestenja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDostavljeno complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDostavljeno">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Imenovanom" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Arhivi" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDostavljeno")
public class TDostavljeno {

    @XmlAttribute(name = "Imenovanom")
    protected Boolean imenovanom;
    @XmlAttribute(name = "Arhivi")
    protected Boolean arhivi;

    /**
     * Gets the value of the imenovanom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isImenovanom() {
        if (imenovanom == null) {
            return false;
        } else {
            return imenovanom;
        }
    }

    /**
     * Sets the value of the imenovanom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImenovanom(Boolean value) {
        this.imenovanom = value;
    }

    /**
     * Gets the value of the arhivi property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isArhivi() {
        if (arhivi == null) {
            return false;
        } else {
            return arhivi;
        }
    }

    /**
     * Sets the value of the arhivi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setArhivi(Boolean value) {
        this.arhivi = value;
    }

}
