package com.xmlproject.project_poverenik.ws.mail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.140+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/mail", name = "MailInterface")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MailInterface {
    
    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/mail", partName = "return")
    public boolean sendMail(
    		@WebParam(partName = "subject", name = "subject") String subject,
    		@WebParam(partName = "body", name = "body") String body,
    		@WebParam(partName = "recipients", name = "recipients") String[] recipients
    		);
    
}
