//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 05:25:10 PM CET 
//


package com.xmlproject.project_poverenik.model.xml_korisnik;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Licne_informacije" type="{http://ftn.uns.ac.rs/xml_korisnik}TLicne_Informacije"/>
 *         &lt;element name="Autorizacija_Informacije" type="{http://ftn.uns.ac.rs/xml_korisnik}TAutorizacija_Informacije"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "licneInformacije",
    "autorizacijaInformacije"
})
@XmlRootElement(name = "Korisnik")
public class Korisnik {

    @XmlElement(name = "Licne_informacije", required = true)
    protected TLicneInformacije licneInformacije;
    @XmlElement(name = "Autorizacija_Informacije", required = true)
    protected TAutorizacijaInformacije autorizacijaInformacije;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the licneInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link TLicneInformacije }
     *     
     */
    public TLicneInformacije getLicneInformacije() {
        return licneInformacije;
    }

    /**
     * Sets the value of the licneInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLicneInformacije }
     *     
     */
    public void setLicneInformacije(TLicneInformacije value) {
        this.licneInformacije = value;
    }

    /**
     * Gets the value of the autorizacijaInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link TAutorizacijaInformacije }
     *     
     */
    public TAutorizacijaInformacije getAutorizacijaInformacije() {
        return autorizacijaInformacije;
    }

    /**
     * Sets the value of the autorizacijaInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAutorizacijaInformacije }
     *     
     */
    public void setAutorizacijaInformacije(TAutorizacijaInformacije value) {
        this.autorizacijaInformacije = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
