//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 06:08:19 PM CET 
//


package com.organ.project_organ.model.xml_izvestaj;

import com.organ.project_organ.model.xml_opste.TDatum;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PodnetiZahtevi">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OdbijeniZahtevi">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SadrzinaOdbijenihZalbi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SadrzinaOdbijeneZalbe" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DatumPodnosenja" type="{http://ftn.uns.ac.rs/xml_opste}TDatum"/>
 *       &lt;/sequence>
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnetiZahtevi",
    "odbijeniZahtevi",
    "sadrzinaOdbijenihZalbi",
    "datumPodnosenja"
})
@XmlRootElement(name = "Izvestaj")
public class Izvestaj {

    @XmlElement(name = "PodnetiZahtevi", required = true)
    protected PodnetiZahtevi podnetiZahtevi;
    @XmlElement(name = "OdbijeniZahtevi", required = true)
    protected OdbijeniZahtevi odbijeniZahtevi;
    @XmlElement(name = "SadrzinaOdbijenihZalbi", required = true)
    protected SadrzinaOdbijenihZalbi sadrzinaOdbijenihZalbi;
    @XmlElement(name = "DatumPodnosenja", required = true)
    protected TDatum datumPodnosenja;
    @XmlAttribute(name = "about")
    protected String about;

    /**
     * Gets the value of the podnetiZahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link PodnetiZahtevi }
     *     
     */
    public PodnetiZahtevi getPodnetiZahtevi() {
        return podnetiZahtevi;
    }

    /**
     * Sets the value of the podnetiZahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodnetiZahtevi }
     *     
     */
    public void setPodnetiZahtevi(PodnetiZahtevi value) {
        this.podnetiZahtevi = value;
    }

    /**
     * Gets the value of the odbijeniZahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link OdbijeniZahtevi }
     *     
     */
    public OdbijeniZahtevi getOdbijeniZahtevi() {
        return odbijeniZahtevi;
    }

    /**
     * Sets the value of the odbijeniZahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdbijeniZahtevi }
     *     
     */
    public void setOdbijeniZahtevi(OdbijeniZahtevi value) {
        this.odbijeniZahtevi = value;
    }

    /**
     * Gets the value of the sadrzinaOdbijenihZalbi property.
     * 
     * @return
     *     possible object is
     *     {@link SadrzinaOdbijenihZalbi }
     *     
     */
    public SadrzinaOdbijenihZalbi getSadrzinaOdbijenihZalbi() {
        return sadrzinaOdbijenihZalbi;
    }

    /**
     * Sets the value of the sadrzinaOdbijenihZalbi property.
     * 
     * @param value
     *     allowed object is
     *     {@link SadrzinaOdbijenihZalbi }
     *     
     */
    public void setSadrzinaOdbijenihZalbi(SadrzinaOdbijenihZalbi value) {
        this.sadrzinaOdbijenihZalbi = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link TDatum }
     *     
     */
    public TDatum getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDatum }
     *     
     */
    public void setDatumPodnosenja(TDatum value) {
        this.datumPodnosenja = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OdbijeniZahtevi {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "property")
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PodnetiZahtevi {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "property")
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SadrzinaOdbijeneZalbe" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sadrzinaOdbijeneZalbe"
    })
    public static class SadrzinaOdbijenihZalbi {

        @XmlElement(name = "SadrzinaOdbijeneZalbe")
        protected List<String> sadrzinaOdbijeneZalbe;

        /**
         * Gets the value of the sadrzinaOdbijeneZalbe property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sadrzinaOdbijeneZalbe property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSadrzinaOdbijeneZalbe().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSadrzinaOdbijeneZalbe() {
            if (sadrzinaOdbijeneZalbe == null) {
                sadrzinaOdbijeneZalbe = new ArrayList<String>();
            }
            return this.sadrzinaOdbijeneZalbe;
        }

    }

}
