//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 05:25:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://ftn.uns.ac.rs/xml_resenje",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix = "pred", namespaceURI = "http://localhost/predikati/")
        })
package com.xmlproject.project_poverenik.model.xml_resenje;

import javax.xml.bind.annotation.XmlNs;