package com.xmlproject.project_poverenik.ws.zahtev;


import com.xmlproject.project_poverenik.model.xml_zahtev.Zahtev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.140+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/request", name = "ZahtevInterface")
@XmlSeeAlso({com.xmlproject.project_poverenik.model.xml_zahtev.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZahtevInterface {
    
    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/request", partName = "return")
    public Zahtev getRequest(
    		@WebParam(partName = "id", name = "id")
    		String id);
    
}
