//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.22 at 12:32:14 PM CET 
//


package com.xmlproject.project_poverenik.model.xml_zalbanaodluku;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.xmlproject.project_poverenik.model.xml_opste.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_zalbanaodluku package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TTeloZalbeOdlukaZalilacOrgan_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "ZalilacOrgan");
    private final static QName _TTeloZalbeOdlukaAdresa_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "Adresa");
    private final static QName _TTeloZalbeOdlukaOpisZalbe_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "OpisZalbe");
    private final static QName _TTeloZalbeOdlukaZakon_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "Zakon");
    private final static QName _TTeloZalbeOdlukaZalilacOsoba_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "ZalilacOsoba");
    private final static QName _TTeloZalbeOdlukaDatumPodnosenjaZahteva_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "Datum_podnosenja_zahteva");
    private final static QName _TTeloZalbeOdlukaBrojResenja_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "BrojResenja");
    private final static QName _TTeloZalbeOdlukaOrganDonosilacOdluke_QNAME = new QName("http://ftn.uns.ac.rs/xml_zalbanaodluku", "OrganDonosilacOdluke");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_zalbanaodluku
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku }
     * 
     */
    public ZalbaNaOdluku createZalbaNaOdluku() {
        return new ZalbaNaOdluku();
    }

    /**
     * Create an instance of {@link TTeloZalbeOdluka }
     * 
     */
    public TTeloZalbeOdluka createTTeloZalbeOdluka() {
        return new TTeloZalbeOdluka();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Napomene }
     * 
     */
    public ZalbaNaOdluku.Napomene createZalbaNaOdlukuNapomene() {
        return new ZalbaNaOdluku.Napomene();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOrgan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "ZalilacOrgan", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TOrgan> createTTeloZalbeOdlukaZalilacOrgan(TOrgan value) {
        return new JAXBElement<TOrgan>(_TTeloZalbeOdlukaZalilacOrgan_QNAME, TOrgan.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "Adresa", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TAdresa> createTTeloZalbeOdlukaAdresa(TAdresa value) {
        return new JAXBElement<TAdresa>(_TTeloZalbeOdlukaAdresa_QNAME, TAdresa.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "OpisZalbe", scope = TTeloZalbeOdluka.class)
    public JAXBElement<String> createTTeloZalbeOdlukaOpisZalbe(String value) {
        return new JAXBElement<String>(_TTeloZalbeOdlukaOpisZalbe_QNAME, String.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "Zakon", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TZakon> createTTeloZalbeOdlukaZakon(TZakon value) {
        return new JAXBElement<TZakon>(_TTeloZalbeOdlukaZakon_QNAME, TZakon.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOsoba }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "ZalilacOsoba", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TOsoba> createTTeloZalbeOdlukaZalilacOsoba(TOsoba value) {
        return new JAXBElement<TOsoba>(_TTeloZalbeOdlukaZalilacOsoba_QNAME, TOsoba.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDatum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "Datum_podnosenja_zahteva", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TDatum> createTTeloZalbeOdlukaDatumPodnosenjaZahteva(TDatum value) {
        return new JAXBElement<TDatum>(_TTeloZalbeOdlukaDatumPodnosenjaZahteva_QNAME, TDatum.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIdResenja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "BrojResenja", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TIdResenja> createTTeloZalbeOdlukaBrojResenja(TIdResenja value) {
        return new JAXBElement<TIdResenja>(_TTeloZalbeOdlukaBrojResenja_QNAME, TIdResenja.class, TTeloZalbeOdluka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOrgan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ftn.uns.ac.rs/xml_zalbanaodluku", name = "OrganDonosilacOdluke", scope = TTeloZalbeOdluka.class)
    public JAXBElement<TOrgan> createTTeloZalbeOdlukaOrganDonosilacOdluke(TOrgan value) {
        return new JAXBElement<TOrgan>(_TTeloZalbeOdlukaOrganDonosilacOdluke_QNAME, TOrgan.class, TTeloZalbeOdluka.class, value);
    }

}
