package com.xmlproject.project_poverenik.ws.zalba;

import java.util.ArrayList;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xmlproject.project_poverenik.model.xml_zalbanaodluku.ZalbaNaOdluku;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.140+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://soap.spring.com/ws/zalba", name = "ZalbaInterface")
@XmlSeeAlso({com.xmlproject.project_poverenik.model.xml_zalbanaodluku.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZalbaInterface {
    
    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://soap.spring.com/ws/zalba", partName = "return")
    public ArrayList<ZalbaNaOdluku> getZalbe();
    
}