//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.05 at 09:53:30 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn-uns.ac.rs/odbijeni_zahtevi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.organ.project_organ.model.odbijeni_zahtevi;
