
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.organ.project_organ.ws.hello;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.123+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "HelloService",
                      portName = "HelloPort",
                      targetNamespace = "http://soap.spring.com/ws/hello",
                     // wsdlLocation = "classpath:wsdl/Hello.wsdl",
                      endpointInterface = "com.organ.project_organ.ws.hello.Hello")
                      
public class HelloPortImpl implements Hello {

    private static final Logger LOG = Logger.getLogger(HelloPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.spring.soap.ws.hello.Hello#sayHi(java.lang.String text)*
     */
    public String sayHi(String text) {
        LOG.info("Executing operation sayHi");
        System.out.println(text);
        try {
        	System.out.println("Inovked sayHi method");
            return "Hello " + text;
          
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
